name: Deploy

on:
    push:
        branchs: main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install pnpm
              run: npm install -g pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
            - name: Push gh-pages
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: gh-pages
                  FOLDER: dist
                  MESSAGE: "Deploy at {sha}"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
